wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1629275547
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 2
      4: 3.8.11
      5: 0.12.0
      8:
      - 1
      - 3
      - 5
architecture:
  desc: null
  value: CNN
dataset_id:
  desc: null
  value: peds-0192
infra:
  desc: null
  value: AWS
learning_rate:
  desc: null
  value: 0.01
momentum:
  desc: null
  value: 0.2
