wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.11
    start_time: 1629746415
    t:
      1:
      - 2
      - 3
      2:
      - 2
      - 3
      3:
      - 2
      4: 3.8.11
      5: 0.12.0
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 14
dropout:
  desc: null
  value: 0.3
epochs:
  desc: null
  value: 5
pool_size:
  desc: null
  value:
  - 3
  - 3
shear_range:
  desc: null
  value: 0.4
size:
  desc: null
  value: 128
zoom_range:
  desc: null
  value: 0.4
